### ISSUE TITLE
Refering to "Free software"

### ISSUE THREAD

**Issue by civodul** [CoralineAda/contributor_covenant#191]
Hello,

I would like to suggest that the home page at contributor-covenant.org refer to "free software" rather than "open source".  The reason is that I think we should frame things in terms of user freedom; that seems pretty much in line with the humanist focus of the Covenant.

Thoughts?

Ludo'.

**Comment by achadwick** [comment]
There have been arguments about the naming since forever: <https://en.wikipedia.org/wiki/Alternative_terms_for_free_software>. I too prefer "Free", FWIW.

It could be glossed/explained inline. “Free, Libre, or Open Source software has always…” or similar. I think that works, because the distinctions are sort of meaningless for a social code of conduct.

I might write

> Free, Open Source software is the foundation of the Internet. New social networks for creating software together mean this is truer than ever.

because I like to play with <http://www.hemingwayapp.com/>, and these replacement sentences are simpler than the original. [And that's a good thing](https://the-pastry-box-project.net/charlotte-spencer/2015-september-16).

Re. framing. I'm interested in lowering these social barriers to participation so that cooler and more radically useful tools get made. That's why I've led the charge for a CoC in the project I maintain, not really for a pure freedom-ideal. But I still get where you're coming from, I think. Easy participation is a major leg of the (Four Freedoms) freedom to improve software and thus do social good.

**Comment by civodul** [comment]
Andrew Chadwick <notifications@github.com> skribis:

> Re. framing. I'm interested in lowering these social barriers to
> participation so that cooler and more radically useful tools get made.
> That's why I've led the charge for a CoC in the project I maintain,
> not really for a pure freedom-ideal. But I still get where you're
> coming from, I think. Easy participation is a major leg of the (Four
> Freedoms) freedom to improve software and thus do social good.

Exactly.  When talking about social justice, I think it makes sense to
choose the phrase that emphasizes it most.

**Comment by civodul** [comment]
It's unfortunate that only one occurrence in the middle of the text is changed, IMO.  I would like to see the title changed.  WDYT, @CoralineAda ?

(Perhaps it sounds like the good old argument again, but I don't think it's anecdotal; it's about [human values](https://www.gnu.org/philosophy/open-source-misses-the-point.html).)

**Comment by sigmavirus24** [comment]
@civodul would you be satisfied if it was explained that occurrences of 'Open Source' are used to reference Free, Libre, and Open Source projects without resorting to acronyms and without repeating that lengthy name unnecessarily?

In my opinion, the title is fine as it is.

**Comment by vyp** [comment]
@sigmavirus24 Wouldn't it be easier to change it in the title anyway then? Besides, "open source" only occurs on the homepage 8 times, 7 if you don't count the one in 122313e. So I do not think it it would be repeating it *that* much anyway.

But if not that, I'd urge you to reconsider changing it *at least* in the title and the first paragraph. So a grand total of 3/4 times. Especially since:

> Open Source has always been a foundation of the Internet [...]

The first words are a bit misleading, because really it was the free software ideals (the freedom to use, study, modify and share software) that were the foundation of the internet. Open source as a concept came a great few years after the conception of the internet as we know it today. (Specifically 1998, the internet was already a big thing by then.)

From the same link @achadwick presented, https://en.wikipedia.org/wiki/Alternative_terms_for_free_software#Open_source_software (emphasis mine):

> In 1998 the term "open source software" was coined as alternative for "free software". There were several reasons for the proposal of a new term. On one hand a group from the free software ecosystem perceived the Free Software Foundation's attitude on propagandizing the "free software" concept as **"moralising and confrontational"**, which was also associated with the term.

"moralising and confrontational" seems a lot like what people who don't care about social progress and justice would say, wouldn't you say? (I mean I've had similar sentiments said to me many times for being pro-women's rights and pro-lgbtq... i.e. "pro"-humanity.)

My point is not to say that you should switch from saying open source completely, I don't really have a problem with using the term. I understand that language evolves with usage, and that maybe the "open source movement" of today is a lot different than that which sparked it 20 years ago.

But given that the free software concept was actually a lot more involved with the concept of sharing, friendship and community\*, compared to open source which was much more about disregarding and stripping the social aspect of it all in favour of only the technical, practical advantages to using it over proprietary software, I feel it would be fitting to at least mention the words a few more times, especially in the title and in the first paragraph.

\*See the [GNU manifesto](https://www.gnu.org/gnu/manifesto.en.html) circa 1985, which really shows how much the preliminary ideas were based on being kind and nice to each other. Example excerpt:

> Many programmers are unhappy about the commercialization of system software. It may enable them to make more money, but it requires them to feel in conflict with other programmers in general rather than feel as comrades. The fundamental act of friendship among programmers is the sharing of programs; marketing arrangements now typically used essentially forbid programmers to treat others as friends. The purchaser of software must choose between friendship and obeying the law. Naturally, many decide that friendship is more important. But those who believe in law often do not feel at ease with either choice. They become cynical and think that programming is just a way of making money.
>
> By working on and using GNU rather than proprietary programs, we can be hospitable to everyone and obey the law. [...]

Granted of course it's confined within the realms of using and making computer programs, but again point being is that saying "Open Source has always been a foundation of the Internet [...]" is in some ways a bit of an injustice to the movement that "Open Source" spawned from. :/

So here are the changes I would like to see (changes are bolded):

> Contributor Covenant
> A Code of Conduct for **Free, Libre and** Open Source Projects.
>
> **Free software and** Open Source has always been a foundation of the Internet, and with the advent of social open source networks this is more true than ever. But free, libre, and open source projects suffer from a startling lack of diversity, with dramatically low representation by women, people of color, and other marginalized populations.

In any case, thanks for taking the time to read. I love the contributor covenant and how successful it has become, but this has always irked me. And today I felt strongly enough to write about it. (It's funny actually, I feel that the whole naming controversy here is sort of similar to how people wanted to change from just using the terms "gay and lesbian" to using LGBTQ cause it's more inclusive. :) :rainbow_flag:)
