### ISSUE TITLE
Possible inconsistency with religion?

### ISSUE THREAD

**Issue by amoffat** [CoralineAda/contributor_covenant#66]
I'm interested in the CoC, but this line stands out to me:

> We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, or religion.

What if a contributor makes public statements that are consistent with their religious beliefs, but are hostile to another category like gender or sexual orientation?  Are they protected because the covenant does not discriminate against religion?  Or are they not protected because their beliefs are hostile to another group of people?

**Comment by kerrizor** [comment]
No, because that is an impactful action. Here, a brief anecdote might clear this up:

>“Is not this a free country?”
>
>“Yes, sir.”
>
>“Have not I a right to swing my arm?”
>
>“Yes, but your right to swing your arm leaves off where my right not to have my nose struck begins.”

**Comment by amoffat** [comment]
@kerrizor makes sense.

On the other side of the coin:  if maintainers of a project make public pro-LGBT statements, and a potential contributor's religion teaches them that the LGBT community is "wrong" and "sinful", aren't those statements an impactful action that excludes them on the basis of their religion?

**Comment by achadwick** [comment]
@amoffat Not never, but in practice almost certainly not.
It should depends on the nature of the statement and where the bigotry and power differentials lie.
Turning it around again, are *all* statements made in the exercise of one's faith necessarily exclusive of LGBTQ people? The answer to that is emphatically no.

-------------------

(Longwindedly answering the original question; apologies....)
From my reading of 1.1.0, no: not exempted if the public statements are made while publicly representing the project in question, or in the project's own public spaces while taking any role.

As I understand it, adopting the covenant imparts a duty on the adopter to not do harm in the process of contributing to the project, with the goal of fostering a respectful atmosphere between contributors. Much like my choosing to adopt a particular FOSS license tells you that I won't threaten you with LAWSUITE or send the legal sharks after you for modifying my code, so my adopting a CoC tells you that I won't harass or demean you, or send brigades after you just for being gay, or black, a woman, or a Mormon, or trans*, or any of a hundred other differences of being from my white-ass self. That's what both are about: offering guarantees of safety to contribute.

It isn't about protecting the adopter from the consequences of their harmful speech, of from the consequences of abandoning that duty to other contributors. That matters too.

Much like a license, you're free to associate with a project using the covenant if you abide by it, and that necessarily involves tolerating the other contributors. The covenant has the political aim of encouraging marginalized people to contribute when they might not otherwise by asserting that we won't be terrible in specified ways. FOSS licenses like the GPL have the political aim of putting modifiable, inspectable, open software in people's hands by asserting that we won't be litigious when it comes to use or modification.

**Comment by CoralineAda** [comment]
You can hold and speak about religious views without using language that harasses or belittles others. If you must be aggressive in your language, it's best to do that outside the purview of the project, unless those are the values that you are committed to as a project. In which case this CoC is probably not for you.

Make sense?

**Comment by amoffat** [comment]
@CoralineAda I agree.

Mind leaving this issue open for a little while?  I'm interested in seeing more ideas on the topic.

**Comment by doublezeta** [comment]
How can you compare beliefs to actions, such as swinging your arm at someone?

**Comment by kerrizor** [comment]
You are free to believe any mythology you desire, however when your actions based upon that belief impair the rights of others, you are crossing the line. You do not have a right to impose beliefs nor take action against others based on which church/temple/mosque/grove you go to.

**Comment by kerrizor** [comment]
...that said, I don't believe it to be fair, honest, or admirable to discriminate *against* someone due to their beliefs, only upon their actions. Religion, while a choice, holds a special place in the American cultural and legal system (a country in which Coraline and I both hold citizenship.) Further, religious affiliation is treated as a protected class in America.

**Comment by webmaven** [comment]
How about covering atheists as well by changing 'religion or lack thereof'? I can make this a separate issue if you like.

**Comment by CoralineAda** [comment]
Refer to PR https://github.com/CoralineAda/contributor_covenant/pull/83
