### ISSUE TITLE
Politics?

### ISSUE THREAD

**Issue by postmodern** [CoralineAda/contributor_covenant#73]
Should politics be explicitly listed, along with age, race, gender, etc? Can politics be protected, or would that open a loophole for people to claim oppressive opinions (ex: racism) are political opinions.

**Comment by kerrizor** [comment]
No, I don't believe politics need to be protected.

**Comment by doublezeta** [comment]
Why not?

**Comment by postmodern** [comment]
Can someone be harassed due to political beliefs or is that just the nature of political discourse? Not all political ideas are sound or logical, so naturally there will be disagreement.

**Comment by kerrizor** [comment]
Politics are a choice, and part of the structural and cultural traditions of engaging in politics is the exchange of ideas and free debate. You are clearly able to have your own ideas and to express them, but as in the previous case we discussed around lifestyle, your right to swing your arm ends at my nose -- you can have and express beliefs all you want, but you are not protected from ridicule for them. If you want to believe that queer people should be burned alive, you can think that all you like, however the moment you express that (and advocate for) this to happen, you have cross the line into nose-punching territory.

It's a thing that a lot of Americans don't understand. The 1st amendment applies to government organizations, and covers ideas like equal access to the means of speaking as well as to be protected from retaliation, but this only applies to the government; a newspaper owner is not required to print your screed because of it, nor does it protect you from being fired for being a doucheboggen on Facebook.

Every other item in the CoC (and indeed, in most anti-discrimination ordinances and laws) focus on the idea of "protected classes" where one group has either a staggeringly large power imbalance and are thus vulnerable to the majority, or are members of a group who share some trait due to circumstances of birth - gender, sexual identity, race, ethnicity. Politics are not part of your individual identity -- they may certainly **feel** like they are, but they are an expression of social affiliation, and are not an external and inherent part of who you are.

**Comment by doublezeta** [comment]
I don't get why choice keeps getting mentioned here. The code of conduct doesn't mention choice as a guideline, it says everyone should be free of harassment regardless. "Choice" is a very vague and confusing term to base basic human decency on.

**Comment by doublezeta** [comment]
I'll add as a separate thought that some of the identities mentioned in the code of conduct md are not clearly a part of the "not a choice" category. Body weight, for most people is a part of your lifestyle choices about diet and physical fitness. There are some genetic disorders that influence it, but for most people it is within your control whether to be healthy or unhealthy. We don't know why sexual orientation comes from, the brain is a complex organism, it may be genetic, it may come from your early upbringing, or it may just be something that changes overtime like your preference for fruits and vegetables. Religion is generally considered a choice (although some pop science magazines have written about the speculated "god gene"). My point is. choice shouldn't be a relevant factor about whether you respect others, since so many things fall in such a grey area of choice. Science hasn't decided whether most things are a choice or not yet, and ethically I don't believe it should be acceptable to treat someone like shit just because they chose to be that way.

**Comment by kerrizor** [comment]
Choice isn't a guideline, except in the understanding of the nature of legal protections for discrimination. A Code of Conduct isn't meant to be a primer in law, ethics, or morals; you have to bring education and a willingness to engage to the table.

**Comment by postmodern** [comment]
It's confusing to me that religion is listed, but politics is not? Many of the arguments against adding politics could also be applied to religion.

**Comment by CoralineAda** [comment]
I'm adding "political affiliation" to 1.2.0.

**Comment by CoralineAda** [comment]
Refer to PR https://github.com/CoralineAda/contributor_covenant/pull/83

**Comment by postmodern** [comment]
:clap:

**Comment by joliss** [comment]
It's obviously up to you, @CoralineAda, but I'd like to add my 2 cents:

In my professional life, I haven't encountered a case where I thought someone was being discriminated against based on political affiliation. Maybe you have though?

I *have* seen a lot of people saying "I'm against SJWs and you're discriminating against me due to my political beliefs". I worry that having "political affiliation" in a CoC would be seen as giving support to this notion. (My canonical response would be, "well you can wake up one day and decide to stop being bigoted, but I can't wake up one day and decide to stop being a woman in tech".)

So I'd actually prefer not to have "political affiliation" in the CoC. Or perhaps the wording can be improved somehow.

**Comment by postmodern** [comment]
I like how @CoralineAda specified "political _affiliation_". You are free to be affiliated to a political party or ideology, but that doesn't mean you are free to impose those ideas on others nor does it protect those ideas from critique. This applies equally for both ends of the political spectrum. Also, bigotry is not a political ideology.

**Comment by doublezeta** [comment]
@joliss, you have never heard of someone being fired or discriminated against for their beliefs?

**Comment by gortok** [comment]
@CoralineAda From how I read your comment, you added 'political affiliation' to V1.2; but I can't seem to find it in PR #83. Was it dropped?

**Comment by CoralineAda** [comment]
Yes, I changed my mind about political affiliation. The point is to protect underrepresented and/or underprivileged populations, and I don’t think that people are generally oppressed for their political affiliations.

**Comment by gortok** [comment]
@CoralineAda Thanks.  I brought it up because I fear the 'internet mob' will find its way into situations where people are persecuted for their beliefs instead of their actions.  What got me thinking about it was this recent NPR snippet on digital mobs: https://twitter.com/ggreenwald/status/625267060059295745  I've seen it happen in a few places already; and was hoping the Covenant would protect minority beliefs in all cases.

**Comment by mcantelon** [comment]
@CoralineAda People aren't *generally* oppressed (in the West) for their political affiliations, but nor are they generally oppressed for factors in the CoC like "body size" or "personal appearance". These characteristics definitely can factor into harassment/exclusion, though.

**Comment by webmaven** [comment]
@CoralineAda, I'd ask you to reconsider.

As an example, I would object, in any project I was participating in, to someone using the term 'Rethuglican', no matter how much I sympathized with the sentiment, and notwithstanding the fact that people with right-of-center political beliefs are far from being a minority, and certainly not subject to persecution or opression.

@mcantelon, as far as body size and personal appearance goes (BTW, did you have to use "scare quotes"?), people most certainly can be, and often are, oppressed for those factors (and as with so many other things, women get dinged worse than men). How often have you seen an ugly presenter at a conference?

**Comment by tripu** [comment]
> Can someone be harassed due to political beliefs [&hellip;]

@postmodern, yes, and they are being harassed.

> [&hellip;] or is that just the nature of political discourse? Not all political ideas are sound or logical, so naturally there will be disagreement.

Someone could argue the same about other protected aspects: &ldquo;body size&rdquo; and &ldquo;personal appearance&rdquo; are, to an extent, a consequence of personal decisions and lifestyle choices. If my political views are fair game, then my dietary habits, personal hygiene, fashion preferences, usage of scarification, etc. can't be &ldquo;protected&rdquo; either.

More so with religion, as it is 100% a personal choice<sup>⁕</sup>. Allow me to recycle your quote: *&ldquo;is that just the nature of [religious] discourse? Not all [religious] ideas are sound or logical, so naturally there will be disagreement&rdquo;*.

---

<sup>⁕</sup> For all practical purposes. For those poor souls who are *forced* to follow a certain religion under serious threats, the exact wording of this covenant will be the least of their problems.

**Comment by mcantelon** [comment]
@webmaven Sorry, I was just trying to quote the text I was referring to and wasn't trying to imply the stuff's not legitimate, just that political affiliation is seems to be as frequent a reason for being targeted by people.

I would argue that political affiliations are increasingly something people are harassed about and that there is a growing tolerance for the marginalisation of unpopular opinions/people via various means (usually justified using the argument that the opinion/person is inherently oppressive). Ideology and belief generally define popular opinion on who is/isn't privileged and who what's harassment/oppression rather than than legitimate political expression.

**Comment by bladeoflight16** [comment]
@CoralineAda 

> Yes, I changed my mind about political affiliation. The point is to protect underrepresented and/or underprivileged populations, and I don’t think that people are generally oppressed for their political affiliations.

This is the reason why the American founders chose the words "inalienable rights." The only way to have real tolerance or kindness or justice or any virtue is if it applies to everyone, regardless of whether they're over- or underrepresented. A person's wealth does not make them wrong anymore than poorness  makes someone right. A person's out of the ordinary sexual desires does not make them right anymore than being heterosexual makes someone wrong. And certainly these things do not make them less deserving of our fair treatment. Picking the less represented or less privileged as the winners is no more noble than picking those with more representation or privileges, and it's just as dangerous.

**Comment by Aspie96** [comment]
It is in other codes of conduct.
